version: '3.7'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chicken-bot
    ports:
      - "5432:5432"

volumes:
  postgres_data: